"""add table

Revision ID: 00f2a04aed14
Revises: 1b5914ecb24f
Create Date: 2023-08-25 23:00:15.186908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f2a04aed14'
down_revision = '1b5914ecb24f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
